Topic/api 3/create appointment post endpoint
movshov/VA-Audiology-App pull request #28
Opened 2019-05-02 02:02 UTC by Liriaene

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2019-05-02 02:24 UTC, gstone271 commented on api/appointmentsPOST.ts
> +  let tfisurvey_values = [patientid, tfi_i, tfi_sc, tfi_c, tfi_si, tfi_a, tfi_r, tfi_q, tfi_e, tfi_overallscore];
You can use `map` to transform `tfi_datapoints` into this, by turning `name` into `request.body[name]`

2019-05-02 02:25 UTC, gstone271 commented on api/app.ts
> +import appointmentsEndpoint from './appointments'
missing ;

2019-05-02 02:27 UTC, gstone271 commented on api/appointmentsPOST.ts
> +  let tssurvey_sql : string = "INSERT INTO tssurvey (" + ts_datapoints.join(", ") + ") VALUES (" + ts_datapoints.map((value, index) => "$" + (index + 1)) + ") RETURNING *";
You can write a function or loop that does the same thing for all of `tfisurvey_sql`, `thssurvey_sql`, etc. without duplicating code.

2019-05-02 18:49 UTC, ElijahRW approved these changes
Looks good. I agree with  Griffin's suggested edits, but there are no pieces that compromise performance or functionality.

2019-05-02 18:49 UTC, ElijahRW commented on api/appointmentsPOST.ts
> +    leftear_highf_severity, rightear_lowf_configuration, rightear_highf_configuration, leftear_lowf_configuration, leftear_highf_configuration, audiogramtype
This should be pushed out to `root/api-objects` directory as its own class. (Liam will be referencing this when sending data over the API Service

2019-05-02 23:16 UTC, gstone271 commented on api/appointmentsPOST.ts
> +    leftear_highf_severity, rightear_lowf_configuration, rightear_highf_configuration, leftear_lowf_configuration, leftear_highf_configuration, audiogramtype
Per line 85 comment we want to get rid of this class instead.

2019-05-04 00:03 UTC, gstone271 requested changes

2019-05-04 00:03 UTC, gstone271 commented on api/appointmentsPOST.ts
> +  let tfisurvey_sql : string = "INSERT INTO tfisurvey (" + tfi_datapoints.join() + ") VALUES ("+ tfi_datapoints.map((value, index) => request.body[value]) + ") RETURNING *";
This is SQL injectable.

You must always use the $1 $2 etc in the SQL string and then have a separate array of values.
Use an additional call to `map` to generate the array of values.

2019-05-04 05:04 UTC, gstone271 commented on api/appointmentsPOST.ts
> +  let tfi_datapoints : string[]  = [
These arrays of constants can be moved out of `handler`

2019-05-08 02:08 UTC, ElijahRW approved these changes
Could use refactoring in future. (No major security holes)

2019-05-08 02:09 UTC, merged