Topic/api 4/create list accounts endpoint
movshov/VA-Audiology-App pull request #47
Opened 2019-05-12 10:41 UTC by Liriaene

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2019-05-12 16:09 UTC, ElijahRW requested changes
This file should be pushed down into the accounts folder and follow the file naming convention there. Otherwise looks good!

2019-05-12 16:09 UTC, ElijahRW commented on api/accountsGET.ts
> +});
Add authentication to this endpoint.
```suggestion
}, auth.authenticate);
```

You'll need to import the authenticate module to do so:
`import * as auth from './authenticate';`

2019-05-13 01:03 UTC, ElijahRW approved these changes

2019-05-13 02:17 UTC, movshov approved these changes

2019-05-14 20:50 UTC, merged