Admin patient service
movshov/VA-Audiology-App pull request #48
Opened 2019-05-12 17:35 UTC by wynnliam

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Update: new service

* **What is the current behavior?** (You can also link to an open issue here)
There does not exist a class to service admin requests relating to users (create, list users, update users, delete).

* **What is the new behavior (if this is a feature change)?**
Admins can now create a user, get a list of all users, reset password for a user, rename a user, and delete a user.

* **Other information**:
THIS IS JUST THE FRONT-END PART OF THE IMPLEMENTATION. I used a mock server to handle these requests.

2019-05-12 19:47 UTC, ElijahRW requested changes
Looks good. Just pull the Response objects into their own classes and rewrite the endpoints to hit `account/XYZ`.

2019-05-12 19:47 UTC, ElijahRW commented on src/app/services/admin-patient.service.ts
> +  public password: string;
ResetPasswordResponse should be declared in external object under the `api-objects` folder

2019-05-12 19:47 UTC, ElijahRW commented on src/app/services/admin-patient.service.ts
> +export class UserListItem {
UserListItem should be declared in external object under the `api-objects` folder

2019-05-12 19:47 UTC, ElijahRW commented on src/app/services/admin-patient.service.ts
> +    return this.serverApiService.get<UserListItem[]>('/user/list');
List users will hit the endpoint `/accounts`.
Refer to [Dante's PR](https://github.com/movshov/VA-Audiology-App/pull/47/files) to view exactly what variables will be returned with this request:

2019-05-12 19:47 UTC, ElijahRW commented on src/app/services/admin-patient.service.ts
> +    let params : Map<string, string> = new Map();
you can simplify this map constructor
```suggestion
    let params : Map<string, string> = new Map([['name', name]);
```

2019-05-12 19:47 UTC, ElijahRW commented on src/app/services/admin-patient.service.ts
> +export class GenericAdminPatientResponse {
I think this should just be called AdminPatientResponse

2019-05-12 19:47 UTC, ElijahRW commented on src/app/services/admin-patient.service.ts
> +    return this.serverApiService.post<ResetPasswordResponse>('/user/resetPassword', { 'name': name });
Refer to Griffin's PR: the service should hit the endpoint `/accounts/resetPassword`

2019-05-12 19:47 UTC, ElijahRW commented on src/app/services/admin-patient.service.ts
> +    return this.serverApiService.post<GenericAdminPatientResponse>('/user/create', {'name': name, 'password': password, 'type': type});
Refer to Griffin's merged branch: https://github.com/movshov/VA-Audiology-App/pull/42
Service should hit the endpoint `/accounts/create`

2019-05-13 03:00 UTC, MishalAlajmi-psu requested changes
I think the functions should be declared to return an observable of the type you need. You can look at Dominic's  api-users-crud-service.ts on how to do that. and change the endpoints like Elijah mentiond, since we already have a service that does a service that handles user operations

2019-05-13 03:00 UTC, MishalAlajmi-psu commented on src/app/services/admin-patient.service.ts
> +
All of these objects can be combined into one, and be placed into `/api-objects`. I also think that a more appropriate name should be AdminPatientRequest. Since, you're sending a request to the server.

2019-05-14 07:23 UTC, closed without merging