Create patient
movshov/VA-Audiology-App pull request #69
Opened 2019-05-21 18:53 UTC by ElijahRW

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
    * Added 'Patient Login' Component
    * Connected Patient Login to Api Service
    * Fixed `CreatePatient` API to service First name, Last name, email
        * API now automatically generates ID instead of asking customer for input
    * Disconnected Patient-Checking component

2019-05-21 20:07 UTC, OkapalDominic commented on src/app/patient-login/patient-login.component.html
> +      <th>New ID</th>
This should be removed since we don't know the new patient id until a new patient is created.

2019-05-21 20:07 UTC, OkapalDominic commented on src/app/patient-login/patient-login.component.html
> +        <td>{{nextId}}</td>
This should be removed since we don't know the new patient id until a new patient is created.

2019-05-21 20:13 UTC, OkapalDominic requested changes
Probably remove the commented out code as well.  But we really shouldn't have a blank id field in the create a new patient area.

2019-05-21 22:26 UTC, OkapalDominic approved these changes

2019-05-22 02:39 UTC, ElijahRW commented on src/app/patient-login/patient-login.component.ts
> +    // else display error
```suggestion
```

2019-05-22 02:40 UTC, merged