Connected change-password
movshov/VA-Audiology-App pull request #76
Opened 2019-05-23 08:15 UTC by ElijahRW

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
     * Connected Client's password change function (in my-account component) to the service and API

2019-05-23 09:19 UTC, Liriaene approved these changes
Changes look goo to me.

2019-05-23 18:37 UTC, OkapalDominic requested changes
The snackbar notification could be easily missed, and the component is already setup to easily give more visual feedback when the password is wrong.

2019-05-23 18:37 UTC, OkapalDominic commented on src/app/my-account/my-account.component.ts
> +        });
If the old password doesn't match there should be a message and password field color change, similar to how validating the rest of it works.
```suggestion
        }, () => {
          this.passColors.oldPass = this.colors.red;
          this.messages.message = 'Old Password Is Invalid!';
        });
```

2019-05-27 20:29 UTC, ElijahRW commented
Removing PR for updated branch that fixes double commits

2019-05-27 20:29 UTC, closed without merging