added load patient appointments button
movshov/VA-Audiology-App pull request #86
Opened 2019-05-28 02:23 UTC by ElijahRW

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
   * Added and connected a `Load Appointments` button to the Patient List.
   * Renamed `Search` menu tab to `Search Appointments` tab.
   * Added `Search Appointments` tab to the admin page.

2019-05-28 17:11 UTC, MishalAlajmi-psu requested changes

2019-05-28 17:11 UTC, MishalAlajmi-psu commented on client/src/app/audiologist-navigation/navigation-aids.ts
>                  this.tabAvailable.add(TabsEnum.LIST_PATIENTS);
list patients are added twice. line 91 and line 93

2019-05-28 17:58 UTC, OkapalDominic reviewed
Other than what Mishal said, the console.log()s should be removed before merging.
As long as you tested it on a server that has appointments, and it did, in fact, load them, then it looks good otherwise.

2019-05-28 18:48 UTC, gstone271 commented
"Load" is completely ambiguous of what the button actually does. Should clarify that it lists appointments.

2019-05-28 18:49 UTC, gstone271 commented
If you try to load a patient that has no appointments, it wrongly says "Patient ID not found."

2019-06-09 02:25 UTC, OkapalDominic approved these changes

2019-06-09 02:35 UTC, movshov approved these changes

2019-06-09 03:39 UTC, wynnliam approved these changes

2019-06-09 04:58 UTC, MishalAlajmi-psu approved these changes
Looks good!

2019-06-09 19:09 UTC, merged